### ISSUE TITLE
Compatibility with Pinocchio 2.2 & finiteDifferenceIncrement

### ISSUE THREAD

**Issue by nim65s** [humanoid-path-planner/hpp-constraints#102]
Hi,

As foreseen here https://github.com/stack-of-tasks/pinocchio/pull/946#issuecomment-552904615
we have an issue there:

https://github.com/humanoid-path-planner/hpp-constraints/blob/645f97f1154834021191f2f95557c7a782212387/src/differentiable-function.cc#L38

**Comment by jmirabel** [comment]
8187898172e0c5f790f529e121bc21621a8dea98 should fix it.

**Comment by nim65s** [comment]
It works for me, thanks !
