### ISSUE TITLE
Bug in GenericTransformation

### ISSUE THREAD

**Issue by florent-lamiraux** [humanoid-path-planner/hpp-constraints#14]
There seems to be a bug in class GenericTransformation.
I pushed a new test to point out the issue. I tried to fix it myself, but the code is rather technical.
In the test, there seems to be a mismatch in dimensions. I also observed non converging behavior when flag is set to true only for the two first components.

**Comment by jmirabel** [comment]
In the test you added, the following 
```c++
check_consistent (device,
  deprecated::RelativeTransformation::create ("RelativeTransformation", device, ee1, ee2, Transform3f (), Transform3f (), mask),
  RelativeTransformation::create ("RelativeTransformation", device, ee1, ee2, Transform3f (), Transform3f (), mask),
  -1);
```
should be:
```c++
check_consistent (device,
  deprecated::RelativeTransformation::create ("RelativeTransformation", device, ee1, ee2, Transform3f (), Transform3f (), mask),
  RelativeTransformation::create ("RelativeTransformation", device, ee1, ee2, Transform3f (), Transform3f (), mask)
);
```
without the last arguments.

The problem with the deprecated version is that they are not coherent with one another.

What is the bug you encountered ?

**Comment by jmirabel** [comment]
By briefly looking at the code, there is a typo at line 391:
```cpp
 else d_.fullPos = false;
```
should be:
```cpp
 else d_.fullOri = false;
```
but I don't think it matters...
