### ISSUE TITLE
Normalization assert

### ISSUE THREAD

**Issue by nim65s** [humanoid-path-planner/hpp-constraints#174]
Hi, 

In the current master & devel branches, in debug, `Assertion 'hpp::pinocchio::checkNormalized( LiegroupElement(d.value, LiegroupSpace::R3xSO3()))'` is raised in multiple places, ref https://gitlab.laas.fr/humanoid-path-planner/hpp-constraints/-/jobs/188382

**Comment by florent-lamiraux** [comment]
We should replace the following tests:
https://github.com/humanoid-path-planner/hpp-constraints/blob/afbbfa5170836b809eb367e9194c7e02d1445c6b/src/generic-transformation/helper.hh#L350
by something like
```
assert(!ose3 || hpp::pinocchio::checkNormalized(
        LiegroupElement(d.value.tail<4>(), LiegroupSpace::SO3())));
```
but I am unable to write this in a way that the compiler understands.

**Comment by florent-lamiraux** [comment]
Solved by https://github.com/humanoid-path-planner/hpp-constraints/pull/175.
