### ISSUE TITLE
Implicit and explicit constraint solver should be improved

### ISSUE THREAD

**Issue by florent-lamiraux** [humanoid-path-planner/hpp-constraints#38]
Class solver::BySubstitution (previously HybridSolver) is neither clear, nor self-contained:
  - there is no way to add a constraint without knowing whether it is explicit or implicit
  - the users needs to notify to the BySubstitution instance when he has inserted an explicit constraint so that this later recomputes internal data.
  - there are a few protected attributes that are unclear: reducedDimension_, dimension_, reduction_.

I suggest that we clean up this class by re-implementing add method using the code of ConfigProjector::add.

For that, we probably need to migrate classes from hpp-core to hpp-constraints.

**Comment by jmirabel** [comment]
I think this is now solved.
