### ISSUE TITLE
Right hand sides of constraints

### ISSUE THREAD

**Issue by florent-lamiraux** [humanoid-path-planner/hpp-constraints#77]
In the current version of the software, class Implicit stores a right hand side, a value and jacobian.

It seems that those members are not used since the commonly used solvers solver::HierarchicalIterative and solver::BySubstitution handle themself those values.

To make things clearer, I intend to make the following methods deprecated in class Implicit:
  - void rightHandSideFromConfig (ConfigurationIn_t config),
  - vectorIn_t rightHandSide () const,
  - size_type rhsSize (),
  - vectorOut_t nonConstRightHandSide (),
  - vector_t& value (),
  - matrix_t& jacobian ()

Method rhsSize will be replaced by rightHandSideSize and will return the number of "Equality" comparators for homogeneity with solver classes.

Does anyone have an opinion?

**Comment by jmirabel** [comment]
I agree with these changes.

**Comment by florent-lamiraux** [comment]
Those methods are however used in the following places:
- https://github.com/humanoid-path-planner/hpp-manipulation/blob/05cfdf973a419f7f89c1a67d62ddfd505d05506d/src/steering-method/cross-state-optimization.cc#L301
- https://github.com/humanoid-path-planner/hpp-manipulation/blob/05cfdf973a419f7f89c1a67d62ddfd505d05506d/src/steering-method/cross-state-optimization.cc#L318
- https://github.com/humanoid-path-planner/hpp-manipulation/blob/05cfdf973a419f7f89c1a67d62ddfd505d05506d/src/steering-method/cross-state-optimization.cc#L387
- https://github.com/humanoid-path-planner/hpp-manipulation/blob/05cfdf973a419f7f89c1a67d62ddfd505d05506d/src/steering-method/cross-state-optimization.cc#L393
- https://github.com/humanoid-path-planner/hpp-manipulation/blob/05cfdf973a419f7f89c1a67d62ddfd505d05506d/src/steering-method/cross-state-optimization.cc#L475

**Comment by florent-lamiraux** [comment]
and here:
- https://github.com/humanoid-path-planner/hpp-wholebody-step/blob/cbc0a7ea853ea2faaa9d5c7a92c29fadadfbc47a/include/hpp/wholebody-step/time-dependant.hh#L39
- https://github.com/humanoid-path-planner/hpp-wholebody-step/blob/cbc0a7ea853ea2faaa9d5c7a92c29fadadfbc47a/include/hpp/wholebody-step/time-dependant-path.hh#L101

**Comment by jmirabel** [comment]
1. The implementation of this steering method is not fully complete.
2. We could compute the right hand side using the solver. It wouldn't change much the code. We only have to check the solver methods that compute it.

**Comment by florent-lamiraux** [comment]
Note that method rightHandSideAt
- does not return anything if rhsFunction_ is set,
- uses internal member rhs_:
https://github.com/humanoid-path-planner/hpp-constraints/blob/b3e7986feda583acf09e7ed46d54ff1fdbeb1ab7/src/implicit.cc#L55.

Here, https://github.com/humanoid-path-planner/hpp-constraints/blob/b3e7986feda583acf09e7ed46d54ff1fdbeb1ab7/src/solver/hierarchical-iterative.cc#L493,
shouldn't we store the right hand side of the function in the solver as for constant right hand side ?

**Comment by jmirabel** [comment]
I think we should modify the API of class Implicit.

Let us define 2 sizes for the right hand side:
- constraint dimension, equals to the function outputSize.
- *parameterizable* size, equals to the number of non-zero lines.

Then, apply the following change to class Implicit:
1. add a getter for the two sizes defined above, with clear name not refering to rhs.
1. remove of getters of the right hand side.
2. all function computing / modifying the right hand side take as argument a vectorOut_t of the correct size (which ?).
4. add a getter of the MatrixBlock that allows to view the reduced right hand side, from the full right hand side.

For constraints whose right hand side takes value in non-vector space, we should enforce (at least for now) that the comparison type be EQUAL_TO_ZERO.

I propose to have an oral discussion on that.

**Comment by florent-lamiraux** [comment]
Finally, I partially did what I announced. Class Implicit still store the right hand side, but value and Jacobian habe been removed.
