### ISSUE TITLE
minor: build failed on Arch

### ISSUE THREAD

**Issue by nim65s** [humanoid-path-planner/hpp-constraints#90]
Hi,

I got the following build failure on Arch:
```
…/hpp-constraints-4.6.0/src/generic-transformation.cc:162:76: error: no matching function for call to 'liegroupSpace<hpp::constraints::GenericTransformation<6>::ComputePosition, hpp::constraints::GenericTransformation<6>::ComputeOrientation, hpp::constraints::GenericTransformation<6>::OutputSE3>(std::vector<bool>&)'
…/hpp-constraints-4.6.0/src/generic-transformation.cc:166:76: error: no matching function for call to 'indices<hpp::constraints::GenericTransformation<6>::ComputePosition, hpp::constraints::GenericTransformation<6>::ComputeOrientation, hpp::constraints::GenericTransformation<6>::OutputSE3>(std::vector<bool>&)'
```

GCC 9.1.0
Eigen 3.3.7
Boost 1.69.0

As this doesn't happen on 14.04, 16.04 & 18.04, this bug report is only a notice, which can be dismissed at will.

**Comment by jmirabel** [comment]
I am surprised by the GCC version. On 18.04, `gcc --version` gives
```
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
```
Why is the difference so high ?

**Comment by nim65s** [comment]
Arch is just up-to-date, as usual :)

About 18.04, `apt search gcc|grep '^gcc-'` shows 4.8, 5, 6, 7 & 8.

```
$ apt install -qqy gcc-8
$ gcc-8 --version
gcc-8 (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0
```

**Comment by jmirabel** [comment]
I don't see what's the issue. Can you try :
- to explicitly cast the template arguments to bool,
- or to play with the constness of the function argument ?

**Comment by jmirabel** [comment]
#105 should provide a better fix for this.
